require: rubocop-rspec

AllCops:
  NewCops: enable

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/*.rb'

RSpec/DescribeMethod:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
